apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: Kops
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Kops
  template:
    metadata:
      labels:
        app: Kops
    spec:
      containers:
        - name: Kops
          image: ranjithdocker93/kopsimage:latest
          imagePullPolicy: Always
